# Generated by Django 5.1.2 on 2024-10-14 08:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Examination",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField(help_text="Date of the examination")),
                (
                    "diagnosis",
                    models.CharField(
                        choices=[
                            ("CNV", "Choroidal Neovascularization"),
                            ("DME", "Diabetes-Related Macular Edema"),
                            ("DRUSEN", "Drusen"),
                            ("VMT", "Vitreomacular Traction"),
                            ("NORMAL", "Normal"),
                        ],
                        help_text="Diagnosis of the examination",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Notes for the examination", null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("firstname", models.CharField(help_text="First name of the patient", max_length=255)),
                ("lastname", models.CharField(help_text="Last name of the patient", max_length=255)),
                ("birthdate", models.DateField(help_text="Birthdate of the patient")),
                ("national_id", models.CharField(help_text="National ID of the patient", max_length=255)),
                (
                    "phone",
                    models.CharField(blank=True, help_text="Phone number of the patient", max_length=20, null=True),
                ),
                ("email", models.CharField(blank=True, help_text="Email of the patient", max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NetworkDiagnosis",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("network_name", models.CharField(help_text="Name of the neural network", max_length=255)),
                (
                    "diagnosis",
                    models.CharField(
                        choices=[
                            ("CNV", "Choroidal Neovascularization"),
                            ("DME", "Diabetes-Related Macular Edema"),
                            ("DRUSEN", "Drusen"),
                            ("VMT", "Vitreomacular Traction"),
                            ("NORMAL", "Normal"),
                        ],
                        help_text="Diagnosis from the network",
                        max_length=10,
                    ),
                ),
                (
                    "examination",
                    models.ForeignKey(
                        help_text="Examination of the network diagnosis",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="optidiagnoseapi.examination",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="examination",
            name="patient",
            field=models.ForeignKey(
                help_text="Patient of the examination",
                on_delete=django.db.models.deletion.CASCADE,
                to="optidiagnoseapi.patient",
            ),
        ),
        migrations.CreateModel(
            name="Scan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("photo", models.CharField(help_text="Path to the scan file", max_length=500)),
                (
                    "examination",
                    models.ForeignKey(
                        help_text="Examination of the scan",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="optidiagnoseapi.examination",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
