# Generated by Django 5.1.2 on 2024-10-18 20:10

import optidiagnoseapi.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("optidiagnoseapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="photo",
            field=models.FileField(help_text="Path to the scan file", upload_to=optidiagnoseapi.models.upload_to),
        ),
    ]
