# Generated by Django 5.1.3 on 2024-12-27 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("optidiagnoseapi", "0002_alter_scan_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="networkdiagnosis",
            name="examination",
        ),
        migrations.AddField(
            model_name="networkdiagnosis",
            name="confidence",
            field=models.FloatField(default=0.0, help_text="Confidence of the diagnosis [0-100]"),
        ),
        migrations.AddField(
            model_name="networkdiagnosis",
            name="scan",
            field=models.ForeignKey(
                blank=True,
                help_text="Neural network diagnosis of the scan",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="optidiagnoseapi.scan",
            ),
        ),
        migrations.AlterField(
            model_name="examination",
            name="diagnosis",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CNV", "Choroidal Neovascularization"),
                    ("DME", "Diabetes-Related Macular Edema"),
                    ("DRUSEN", "Drusen"),
                    ("VMT", "Vitreomacular Traction"),
                    ("NORMAL", "Normal"),
                ],
                help_text="Diagnosis of the examination",
                max_length=10,
                null=True,
            ),
        ),
    ]
